### ISSUE TITLE
Docker with secure-password

### ISSUE THREAD

**Issue by lioaslan** [emilbayes/secure-password#22]
Hi,
I use `secure-password` with `docker`, but when I run `docker-compose up`, I receive this error.
```api_1    | > sodium-native@2.4.9 install /api/node_modules/secure-password/node_modules/sodium-native
api_1    | > node-gyp-build "node preinstall.js" "node postinstall.js"
api_1    | 
api_1    | libtool is required, but wasn't found on this system
api_1    | ./configure: line 5: ./configure: not found
api_1    | /api/node_modules/secure-password/node_modules/sodium-native/preinstall.js:119
api_1    |     if (err) throw err
api_1    |              ^
api_1    | 
api_1    | Error: ./configure exited with 127
api_1    |     at ChildProcess.<anonymous> (/api/node_modules/secure-password/node_modules/sodium-native/preinstall.js:149:25)
api_1    |     at ChildProcess.emit (events.js:310:20)
api_1    |     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
api_1    | npm WARN api@0.0.1 No repository field.
api_1    | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
api_1    | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
api_1    | 
api_1    | npm ERR! code ELIFECYCLE
api_1    | npm ERR! errno 1
api_1    | npm ERR! sodium-native@2.4.9 install: `node-gyp-build "node preinstall.js" "node postinstall.js"`
api_1    | npm ERR! Exit status 1
api_1    | npm ERR! 
api_1    | npm ERR! Failed at the sodium-native@2.4.9 install script.
api_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
api_1    | 
api_1    | npm ERR! A complete log of this run can be found in:
api_1    | npm ERR!     /root/.npm/_logs/2020-04-20T07_24_48_237Z-debug.log
```

This is my Dockerfile

```
FROM node:12-alpine
WORKDIR /api
COPY . .
ENTRYPOINT [ "sh", "/api/docker-api-cmd/api-cmd.sh" ]
CMD ["npm", "run", "dev"]
```

This is api-cmd.sh:
```
#!/bin/bash

npm install

#Some cmds here
```

Thanks for any helps

**Comment by emilbayes** [comment]
Hi, see my reply over on https://github.com/sodium-friends/sodium-native/issues/126
