### ISSUE TITLE
INVALID_UNRECOGNIZED_HASH and HASH_BYTES

### ISSUE THREAD

**Issue by ofbeaton** [emilbayes/secure-password#26]
Thank you for this great package, saved me a ton of headaches and I look forward to it saving me more in the future as new hashing algos come out.

If your hash is not HASH_BYTES, you never receive the expected `securePassword.INVALID_UNRECOGNIZED_HASH` result, instead you get `hashBuf must be HASH_BYTES (128)`

I would not expect securePassword to impose it's restrictions on the Buffer or password min/max length on hashes it does not recognize as it's own.

```
 Error: hashBuf must be HASH_BYTES (128)
              at assert (<my project>\node_modules\nanoassert\index.js:21:17)
              at SecurePassword.verify (<my project>\node_modules\secure-password\index.js:126:3)
              at <my project>\node_modules\secure-password\index.js:109:12
              at new Promise (<anonymous>)
              at SecurePassword.verify (<my project>\node_modules\secure-password\index.js:108:12)
              at Object.exports.passwordHashCompareString (<my project>\src\utils\password-hash.ts:37:14)
              at AuthResolver.login (<my project>\src\resolvers\auth-resolver.ts:120:25)
              at processTicksAndRejections (internal/process/task_queues.js:97:5)
              at Object.<anonymous> (<my project>\tests\auth-resolver\login.mutation.errors.test.ts:83:22) {
            locations: [Array],
            path: [Array]
          }
```

I can fix it by re-saving my old hashes with
```
const oldHash = Buffer.alloc(SecurePassword.HASH_BYTES)
oldHash.write(rawOldHash)
```
however this can cause problems with any legacy hashing algorithm so sometimes needs magic to undo it again too.

As an aside, if I want to test `securePassword.VALID_NEEDS_REHASH` works properly in my app, is there a way to generate an "older" hash with securePassword to trigger it? or am I stuck mocking out `pwd.verify` to return this code in my tests?

**Comment by emilbayes** [comment]
Thanks, I should fix this!

To trigger the `VALID_NEEDS_REHASH` is pretty easy, https://github.com/emilbayes/secure-password/blob/3a0cb3712c03787a16b6cd3ef7d588c9cc6b944c/test.js#L154-L158

Basically you can change the memlimit, eg. by setting it one higher or similar.
